### ISSUE TITLE
Decoding issue on Windows 

### ISSUE THREAD

**Issue by thrkll** [mideind/iceweather#2]
Installing the package on Windows via pip or `python setup.py install` will result in an decoding error. 

```
>> python setup.py install

Traceback (most recent call last):
  File "C:\Iceweather\setup.py", line 17, in <module>
    long_description = fh.read()
                       ^^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3747: character maps to <undefined>
```

**Comment by thrkll** [comment]
Should be fixed with pull request #3.

**Comment by vthorsteinsson** [comment]
Takk kærlega fyrir þetta og togbeiðnina - erum búin að samþykkja hana.
